"""add indexes to FK columns

Revision ID: 2e4e0889c062
Revises: 0002_add_remaining_platforms
Create Date: 2026-03-13 07:01:27.585034

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2e4e0889c062'
down_revision: Union[str, None] = '0002_add_remaining_platforms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.create_index(op.f('ix_publication_stats_publication_id'), 'publication_stats', ['publication_id'], unique=False)
    op.create_index(op.f('ix_publications_article_id'), 'publications', ['article_id'], unique=False)
    op.create_index(op.f('ix_publications_platform_id'), 'publications', ['platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_platform_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_article_id'), table_name='publications')
    op.drop_index(op.f('ix_publication_stats_publication_id'), table_name='publication_stats')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    # ### end Alembic commands ###
